### ISSUE TITLE
是要替换目录下的那个文件呀？

### ISSUE THREAD

**Issue by 601958483** [FaridZelli/Nilesoft-Shell-Presets#1]
![Clip_20240427_143915](https://github.com/FaridZelli/Nilesoft-Shell-Presets/assets/43309053/6dedbd33-60ec-47f8-9fe8-cb0856674cb6)
没太看明白

**Comment by FaridZelli** [comment]
您正在使用 Nilesoft Shell 的新版本，但为了使其正常工作，您需要降级到 1.8 Beta 版本，正如描述中所述。🙂

**Comment by 601958483** [comment]
> 您正在使用 Nilesoft Shell 的新版本，但为了使其正常工作，您需要降级到 1.8 Beta 版本，正如描述中所述。🙂

是的，我后来发现了。已解决了，我就关闭了问题，感谢你的回复
